site_name: S.T.A.R.K. Docs
site_author: Mark Parker
site_description: Speach and Text Algorithmic Recognition Kit (S.T.A.R.K.) is a set of tools for building custom voice assistants. It is designed to be modular and extensible, allowing you to build your own custom voice assistant with ease.
site_url: https://stark.markparker.me

repo_name: MarkParker5/STARK
repo_url: https://github.com/MarkParker5/STARK


copyright: Copyright &copy; Mark Parker

nav:
  - Home: index.md
  - Contributing and Shared Usage: contributing-and-shared-usage-stark-place.md
  - Installation: installation.md
  - First Steps: first-steps.md
  - Sync vs Async Commands: sync-vs-async-commands.md
  - Creating Commands: creating-commands.md
  - Dependency Injection: dependency-injection.md
  - Patterns: patterns.md
  - Command Response: command-response.md
  - Commands Context: commands-context.md
  - Voice Assistant: voice-assistant.md
  - Default Speech Interfaces: default-speech-interfaces.md
  - Where to Host: where-to-host.md
  - Advanced:
    - Optimization: advanced/optimization.md
    - Custom Run: advanced/custom-run.md
    - Fallback Command / LLM Integration: advanced/fallback-command-llm-integration.md
    - External Triggers: advanced/external-triggers.md
    - Custom Interfaces: advanced/custom-interfaces.md
    - Localization and Multi-Language: advanced/localization-and-multi-language.md
    - Other: advanced/other.md # TODO: <-
  # - S.T.A.R.K P.L.A.C.E Navigator: /stark-place-navigator.md

theme:
  name: material
  custom_dir: overrides
  language: en

  icon:
    repo: fontawesome/brands/github

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette: 

    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: orange
    #   accent: orange
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: orange
      accent: orange
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: orange
      accent: orange
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra:
  generator: false
  
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/MarkParker5/
  
  features:
    - navigation.footer

  analytics:
    provider: google
    property: G-NMVH5RVSYB

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - offline
  - search
  # - social
  # - optimize
  # - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  # - git-committers:
  #     repository: MarkParker5/STARK
  #     branch: master
