name: publish docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get update && sudo apt-get install -y libjpeg-dev zlib1g-dev # fix Pillow PEP 517 error during installation
      - run: pip install poetry
      - run: poetry install --extras docs
      - run: poetry run mkdocs gh-deploy --force
